In [1]:
import keras
from keras.datasets import mnist
from keras.utils import to_categorical
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
# Step 1: Data Preprocessing (Machine Readable Form)
# Scaling - One Unit Standard Deviation for Numeric Columns
# Fundamental requirement of Deep Learning Networks
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [10]:
# Step 1: Data Preprocessing (Machine Readable Form)
# OneHot Coding for Categorical Data
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [11]:
# Step 2: Build your Network
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [12]:
# Step 3: Compile your Network
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [13]:
# Step 4: Training / Learning your Network
network.fit(train_images,
train_labels,
epochs=5,
batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 12ms/step - loss: 0.2538 - accuracy: 0.9270
Epoch 2/5
469/469 [==============================] - 6s 12ms/step - loss: 0.1037 - accuracy: 0.9693
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0686 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0506 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0366 - accuracy: 0.9889


In [14]:
# Step 5: Performance Evaluation - Test Dataset
# Unseen (Not included in Training Dataset)
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0680 - accuracy: 0.9808
test_acc: 0.9807999730110168


In [17]:
# Step 6: Prediction in Action - New Handwritten Digit - image 28*28
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
import warnings
# load the image via load_img function
img = load_img('E:/7th Semester/Deep Learning & Application/digit0.jpeg', color_mode='grayscale')
# convert the given image into numpy array
NewImage = img_to_array(img)
# convert the given image into numpy array and scalling
NewImage = NewImage.reshape((1, 28 * 28))
NewImage = NewImage.astype('float32') / 255
# Prediction (Label / Answer / Output from the Network)
Prediction = network.predict(NewImage)
Prediction

array([[9.99999881e-01, 4.71274461e-14, 7.64168888e-08, 5.72673964e-10,
        2.58457996e-13, 1.33678815e-11, 3.27957927e-08, 1.67812386e-09,
        2.73782691e-10, 8.52715942e-09]], dtype=float32)

In [18]:
# Output from the List of the Probability, Find out Maximum
class_names = ['Zero','One', 'Two', 'Three', 'Four', 'Five',
'Six', 'Seven', 'Eight', 'Nine']
PredictedDigit = class_names[np.argmax(Prediction)]
PredictedDigit

'Zero'

In [19]:
# Save Model use in FUTURE Use
network.save('HandDigitRecorgnitionModel.h5')